name: WakeUp Neo!

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Run Script
        run: |
          chmod +x ./howareyou.sh
          ./howareyou.sh ${{ vars.TARGET_URL }}
